version: '2'

services:
  web:
    build:
      context: .
    ports:
      - 8000:80
      # - 443:443
    command: sh /init.sh
    volumes:
      - ./:/var/www/html/digging_deeper_laravel
      - ./docker/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/init.sh:/init.sh
      - ./docker/logs/apache2:/var/log/apache2
    depends_on:
      - mysql

  mysql:
    image: mysql
    ports:
      - 6603:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deeper
      MYSQL_USER: deeper
      MYSQL_PASSWORD: deeper
